# Generated by Django 4.1.5 on 2023-02-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0013_alter_orderitem_order_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtext', models.TextField(max_length=3000)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.table')),
            ],
        ),
    ]
