# Generated by Django 4.1.5 on 2023-01-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('available_amount', models.IntegerField()),
                ('group', models.CharField(choices=[('Alchol', 'Alchohol'), ('Cocktail ', 'Cocktail'), ('Grills', 'Grills'), ('Meals', 'Meals')], max_length=250)),
            ],
        ),
    ]
