# Generated by Django 4.1.5 on 2023-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderItem',
            field=models.ManyToManyField(to='order.menuitem'),
        ),
    ]
