# Generated by Django 4.1.5 on 2023-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='amount_ordered',
            field=models.IntegerField(default=0),
        ),
    ]
