# Generated by Django 4.1.5 on 2023-01-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_menuitem_amount_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(choices=[('Alcohol', 'Alchohol'), ('Cocktail ', 'Cocktail'), ('Grills', 'Grills'), ('Meals', 'Meals')], max_length=250),
        ),
    ]
