# Generated by Django 4.1.5 on 2023-01-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_menuitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
