# Generated by Django 4.1.1 on 2023-01-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='amount_ordered',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderItem',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menuitem')),
            ],
        ),
    ]
