# Generated by Django 4.1.5 on 2023-02-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_made',
        ),
    ]
