# Generated by Django 4.1.5 on 2023-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_menuitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
