# Generated by Django 4.1.5 on 2023-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_amount',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(choices=[('Exotic Drinks', 'Exotic Drinks'), ('Cocktail', 'Cocktail'), ('Mocktails', 'Mocktails'), ('Milkshakes', 'Milkshakes'), ('Meals', 'Meals'), ('Tots', 'Tots'), ('Milkshakes', 'Milkshakes')], max_length=250),
        ),
    ]
