# Generated by Django 4.1.5 on 2023-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_menuitem_available_amount_menuitem_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(choices=[('Exotic Drinks', 'Exotic Drinks'), ('Cocktail', 'Cocktail'), ('Mocktails', 'Mocktails'), ('Milkshakes', 'Milkshakes'), ('Meals', 'Meals'), ('Tots', 'Tots')], max_length=250),
        ),
    ]
