# Generated by Django 4.1.5 on 2023-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_menuitem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(choices=[('Exotic Drinks', 'Exotic Drinks'), ('Cocktail', 'Cocktail'), ('Mocktails', 'Mocktails'), ('Milkshakes', 'Milkshakes'), ('Meals', 'Meals'), ('Tots', 'Tots'), ('Regular Drinks', 'Regular Drinks')], max_length=250),
        ),
    ]
