# Generated by Django 4.1.5 on 2023-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_menuitem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(choices=[('Exotic Drinks', 'Exotic Drinks'), ('Cocktail', 'Cocktail'), ('Mocktails', 'Mocktails'), ('Milkshakes', 'Milkshakes'), ('Meals', 'Meals'), ('Tots', 'Tots'), ('Soft Drinks', 'Soft Drinks'), ('Platters', 'Platters'), ('Proteins', 'Proteins'), ('Shisha', 'Shisha')], max_length=250),
        ),
    ]
